repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest stable version of Flake8
    hooks:
      - id: flake8
        args: [--max-line-length=88]
        additional_dependencies: 
          - flake8-bugbear               # Optional, for advanced linting
